-- MySQL Script generated by MySQL Workbench
-- Wed Sep 19 19:13:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`members` (
  `id` INT NOT NULL,
  `aw_id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `aw_id_UNIQUE` (`aw_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tags` (
  `id` INT NOT NULL,
  `name` TEXT NULL,
  `type` INT NULL DEFAULT 1:member, 2:skill,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member_tags` (
  `id` INT NOT NULL,
  `members_id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tag_relations_members_idx` (`members_id` ASC),
  INDEX `fk_member_tags_tags1_idx` (`tags_id` ASC),
  CONSTRAINT `fk_tag_relations_members`
    FOREIGN KEY (`members_id`)
    REFERENCES `mydb`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `mydb`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`skills` (
  `id` INT NOT NULL,
  `name` TEXT NULL,
  `layer` INT NULL DEFAULT 0,
  `parent` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member_skills` (
  `id` INT NOT NULL,
  `members_id` INT NOT NULL,
  `skills_id` INT NOT NULL,
  `level` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_member_skills_skills1_idx` (`skills_id` ASC),
  INDEX `fk_member_skills_members1_idx` (`members_id` ASC),
  CONSTRAINT `fk_member_skills_skills1`
    FOREIGN KEY (`skills_id`)
    REFERENCES `mydb`.`skills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_skills_members1`
    FOREIGN KEY (`members_id`)
    REFERENCES `mydb`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`skill_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`skill_tags` (
  `id` INT NOT NULL,
  `skills_id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_skill_tags_skills1_idx` (`skills_id` ASC),
  INDEX `fk_skill_tags_tags1_idx` (`tags_id` ASC),
  CONSTRAINT `fk_skill_tags_skills1`
    FOREIGN KEY (`skills_id`)
    REFERENCES `mydb`.`skills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skill_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `mydb`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
